[package]
name = "rts"
edition = "2021"
authors = ["miruji <miruji@protonmail.com>"]
description = "Real-Time Programming Language of Free Data Structures"
license-file = "LICENSE.md" # FCL
readme = "README.md"

# ======================================================================================================================

autobins = false
autoexamples = false
autotests = false
autobenches = false

publish = false

# ======================================================================================================================

[dependencies]
termion = { version = "4.0.5", optional = true }
rand = { version = "0.9.2", optional = true }
wasm-bindgen = {  version = "0.2", optional = true }
serde_json = { version = "1.0.149", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }

# todo smmalloc = { version = "7.6.4", optional = true }
#  Но по тестам он самый лучший от остальных вел себя, 
#  но все равно это надо подумать будет потом - сейчас мало смысла.

chillffi = { version = "0.4.0", optional = true }
# todo desc

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Oz', '--enable-bulk-memory'] # Нужно было для билда wasm с opt

# ======================================================================================================================

[lib]
name = "rts"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"] # cdylib → WASM/FFI, rlib → внутреннее использование

[[bin]]
name = "rts"
path = "src/main.rs"

# ======================================================================================================================

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
overflow-checks = false
debug  = false
incremental = false
rpath = false

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
lto = false
incremental = true

# ======================================================================================================================

[features]

# test:
# cargo test
# cargo test --lib

# cargo build
default = ["termion","rand","serde","chillffi"]

# ======================================================================================================================

# test:
# cargo test --features analyzer --lib
analyzer = [
  "wasm-bindgen",
  "serde_json",
  "serde",
  # todo Можно использовать wasm allocator ? ну если он будет лучше;
  #  Хотя какой смысл если он будет в байтах записан? Или не будет?
  #  В общем, большие сомнения по этому поводу.
]

# ======================================================================================================================

[lints.rust]
non_snake_case = "allow"
non_upper_case_globals = "allow"
non_camel_case_types = "allow"

# ======================================================================================================================

[lints.clippy]
unused_unit = "allow"
option_if_let_else = "allow"
collapsible_if = "allow"
too_long_first_doc_paragraph = "allow"
len_without_is_empty = "allow"
suspicious_else_formatting = "allow"
doc_lazy_continuation = "allow"
type_complexity = "allow"
nursery = { level = "warn", priority = -1 } # At the very bottom

# ======================================================================================================================