[package]
name = "rts"
edition = "2021"
authors = ["miruji <miruji@protonmail.com>"]
description = "Reactive Scripting Language of Free Data Structures"
license-file = "LICENCE"
readme = "README.md"

[dependencies]
termion = "1.5"
lazy_static = "1.4.0"
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["full"] }
reqwest = { version = "0.12.8", features = ["json", "blocking"] }
serde_json = "1.0.128"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
overflow-checks = false
debug  = false
incremental = true
rpath = false

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
lto = false
incremental = true